version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  devices:
    build:
      context: ./packages/devices
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  telemetry:
    build:
      context: ./packages/telemetry
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  api-gateway:
    build:
      context: ./packages/api-gateway
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DEVICES_SERVICE_URL=http://devices:3000
      - TELEMETRY_SERVICE_URL=http://telemetry:3001
    depends_on:
      - devices
      - telemetry
