apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
        - name: telemetry
          image: maratnasyrov/telemetry-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_HOST
              value: 'postgres-service'
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USER
              value: 'app_user'
            - name: DATABASE_PASSWORD
              value: 'app_password'
            - name: DATABASE_NAME
              value: 'telemetry_db'

---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
spec:
  selector:
    app: telemetry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
