apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-management
  template:
    metadata:
      labels:
        app: device-management
    spec:
      containers:
        - name: device-management
          image: maratnasyrov/device-management-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: 'postgres-service'
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USER
              value: 'app_user'
            - name: DATABASE_PASSWORD
              value: 'app_password'
            - name: DATABASE_NAME
              value: 'device_db'

---
apiVersion: v1
kind: Service
metadata:
  name: device-management-service
spec:
  selector:
    app: device-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
