version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: device_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend

  device-management-service:
    build:
      context: ./smart-home-microservices/device-management-service
      dockerfile: Dockerfile
    container_name: device-management-service
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=app_user
      - DATABASE_PASSWORD=app_password
      - DATABASE_NAME=device_db
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - backend

  telemetry-service:
    build:
      context: ./smart-home-microservices/telemetry-service
      dockerfile: Dockerfile
    container_name: telemetry-service
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=app_user
      - DATABASE_PASSWORD=app_password
      - DATABASE_NAME=device_db
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
