apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: 'app_user'
            - name: POSTGRES_PASSWORD
              value: 'app_password'
            - name: POSTGRES_DB
              value: 'device_db'
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d/init-db.sh
              name: init-db-script
              subPath: init-db.sh
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: init-db-script
          configMap:
            name: init-db-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
